name: Build artifacts

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-bun:
    strategy:
      fail-fast: false
      matrix:
        target:
          - bun-linux-x64
          - bun-linux-arm64
          - bun-windows-x64
          - bun-darwin-x64
          - bun-darwin-arm64
          - bun-linux-x64-musl
          - bun-linux-arm64-musl
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bun/

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9

      - run: bun install
      - run: bun run build ${{ matrix.target }}

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target }}
          path: bun/dist/
          if-no-files-found: error

  build-deno:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deno/

    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: 2.6.10

      - run: deno task build ${{ matrix.target }}

      - uses: actions/upload-artifact@v6
        with:
          name: deno-${{ matrix.target }}
          path: deno/dist/
          if-no-files-found: error

  build-node:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: node/

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 25.6.1

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v6
        with:
          name: node-${{ matrix.os }}
          path: node/dist/
          if-no-files-found: error
