name: Build artifacts

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-bun:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        source:
          - get
          - get-pkg
        target:
          - bun-linux-x64
          - bun-linux-arm64
          - bun-windows-x64
          - bun-darwin-x64
          - bun-darwin-arm64
          - bun-linux-x64-musl
          - bun-linux-arm64-musl

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9

      - run: bun ci
      - run: bun run build:${{ matrix.source }}:bun ${{ matrix.target }}

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target }}
          path: dist/bun/
          if-no-files-found: error

  build-deno:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        source:
          - get
          - get-pkg
        target:
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: 2.6.10

      - run: deno install
      - run: deno task build:${{ matrix.source }}:deno ${{ matrix.target }}

      - uses: actions/upload-artifact@v6
        with:
          name: deno-${{ matrix.target }}
          path: dist/deno/
          if-no-files-found: error

  build-node:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        source:
          - get
          - get-pkg
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 25.7.0

      - run: node --run build:${{ matrix.source }}:node

      - uses: actions/upload-artifact@v6
        with:
          name: node-${{ matrix.os }}
          path: dist/node/
          if-no-files-found: error
